### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by popovae** [inspace-io/INSElectronicProgramGuideLayout#1]
Hi guys!

First of all I want to say that the work youэму done is awesome!
I have a few questions:
1) Is there any easy way to make the Y axe with bigger steps - I mean for example now the step is 30 minutes, is there any way to make it 1 hour to make everything more compact in time frame?
2) What is the best way to update data shown? For example delete everything and pull new data...or add new Channel or Programme to the channel...

Thank you!!!

**Comment by m1entus** [comment]
1) You have self.hourWidth property, by default it is 600points
2) 
    [self.collectionViewCalendarLayout invalidateLayoutCache];
    [self.collectionView reloadData];

**Comment by m1entus** [comment]
1) You have self.hourWidth property, by default it is 600points
2) 
    [self.collectionViewEPGLayout invalidateLayoutCache];
    [self.collectionView reloadData];

**Comment by popovae** [comment]
Thank you m1entus!!!
1) Actually I wanted to make it not just visually, but remove unnecessary steps...so in will go something like 13:00 14:00 15:00, not just compress it, but make steps larger... Sorry for my explanations, hope you get it)))

**Comment by m1entus** [comment]
Remove decorators view for half hour header:

[self.collectionViewEPGLayout registerClass:ISHalfHourLineView.class forDecorationViewOfKind:INSEPGLayoutElementKindHalfHourVerticalGridline];

and

 [self.collectionView registerNib:[UINib nibWithNibName:timeRowHeaderStringClass bundle:nil] forSupplementaryViewOfKind:INSEPGLayoutElementKindHalfHourHeader withReuseIdentifier:timeRowHeaderStringClass];

**Comment by popovae** [comment]
Sorry to ask too many questions, but if I will need to make it with 4 hour or 12 hour step?) I meen it must be somewhere in the code the calculation of steps...

**Comment by m1entus** [comment]
https://github.com/inspace-io/INSElectronicProgramGuideLayout/blob/master/INSElectronicProgramGuideLayout/INSElectronicProgramGuideLayout.m#L555
