### ISSUE TITLE
How can I use it with swift 3?

### ISSUE THREAD

**Issue by ssaguiar** [inspace-io/INSElectronicProgramGuideLayout#13]
I have downloaded the program guide and wish to use it in my project.
I have dded it using pod and in my bridging have put:
#import "INSElectronicProgramGuideLayout/INSElectronicProgramGuideLayout.h"

I also copied the Electronic Program Guide Cene to my storyboard.
I have created a segue from a button to the cene.
I also created a class called EpgViewController as:

import UIKit

class EpgViewController: UICollectionViewController
{
}

Now, when I click the button to show the empty cene, I get this error:

2017-05-09 17:40:30.660719-0300 ipTv3[884:169392] -[ipTv3.EpgViewController currentTimeForCollectionView:layout:]: unrecognized selector sent to instance 0x167b7530
2017-05-09 17:40:30.663947-0300 ipTv3[884:169392] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ipTv3.EpgViewController currentTimeForCollectionView:layout:]: unrecognized selector sent to instance 0x167b7530'
*** First throw call stack:
(0x1d93bb3d 0x1cbc3067 0x1d940fd1 0x1d93f0c3 0x1d867d08 0x1d6a25f 0x1d663b9 0x1d63939 0x1d627bb 0x22bc57c3 0x22bc4db1 0x22bc47ab 0x22b678c3 0x207c4cb7 0x207b8d77 0x207b8c05 0x20747849 0x20765feb 0x20766b3f 0x1d8f7803 0x1d8f5a55 0x1d8f6017 0x1d8490ef 0x1d848f11 0x1eff3b41 0x22bcde83 0x170e94 0x1d0364eb)
libc++abi.dylib: terminating with uncaught exception of type NSException

Do you have any example on how to implement the INSElectronicProgramGuideLayout using swift?

Thank you very much for any help.

**Comment by m1entus** [comment]
Yes it can be used and you are doing it wrong, you havn't implement required delegate methods.

**Comment by kushalhyperlink** [comment]
Hello @m1entus 

Hope you are doing good!

Is there any chance of the swift version library demo?

**Comment by m1entus** [comment]
Hey, no i am not seeing a reason to make swift version demo of this library, because it is just custom collectionview layout

**Comment by warln10** [comment]
hi @m1entus  can you provide example using swift it would be greatful
