### ISSUE TITLE
Scrolling to arbitrary time

### ISSUE THREAD

**Issue by tomassliz** [inspace-io/INSElectronicProgramGuideLayout#15]
I would like to scroll to arbitrary time and not only to the current time.

**Comment by m1entus** [comment]
It should not be hard to implement it, PR welcome!

**Comment by aatalyk** [comment]
@tomassliz hi, were you able to add this scroll method?

**Comment by tomassliz** [comment]
@aatalyk Hi, yes, I was able to implement this behavior in some way. But it’s long time ago and I don’t remember the exact implementation. Why you’re asking?

**Comment by aatalyk** [comment]
I just needed to implement same method, nevermind I was able to implement that :)

**Comment by m1entus** [comment]
So please make PR, then next one will not have same problem ;)

**Comment by aatalyk** [comment]
Sure, I will send PR asap
