### ISSUE TITLE
How to make time row always visible?

### ISSUE THREAD

**Issue by hansolowireless** [inspace-io/INSElectronicProgramGuideLayout#17]
How to make the time row always visible when scrolling, just like the channel column? Thanks!

**Comment by AdnanAliShabir** [comment]
How to achieve this one? I want time visible always. if we scroll the collectionView it is disappear.

**Comment by AdnanAliShabir** [comment]
@hansolowireless @m1entus 
Is it possible? Thanks

**Comment by m1entus** [comment]
Everything is possible, you should easly implement it, you have already big bunch of code which you should be grateful which you can based on.

**Comment by AdnanAliShabir** [comment]
@m1entus 
I'm very thankful for what you have done already it's really great. Actually i don't have too much experience in objective c so it will be very helpful for me if you guide me or provide some demo code.
Thanks.
