### ISSUE TITLE
"Minimum" start/end time for collection view.

### ISSUE THREAD

**Issue by manumax** [inspace-io/INSElectronicProgramGuideLayout#4]
Hi,
  regarding #2, I've found out a potential improvement but I don't know if it could be of any interest to the project.
  On that pull request, delegate has been extended to let lib's clients to define a fixed start/end time instead of showing only the interval of time derived by the start/end time of each cell.
  A possible improvement (that I'm already using) is to intend those fixed start/end time as "minimum" values. In this way, is it possible to define a minimum size for the collection view, but it is still possible to present cells that are outside the given range.
  What do you think?

**Comment by m1entus** [comment]
You will have to set contentInset of collectionView, then you will have limit and cell will be still outside the given range, you can use delegates, add visible range to minimum and maximum time and set contentInset - visible range

**Comment by manumax** [comment]
I'm going to close this since proposed improvement doesn't seem such useful. Thank you!
