### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by delannoyk** [inspace-io/INSElectronicProgramGuideLayout#5]
Hi,

I'm having an issue with the time needed to layout the collection view.

I have approximatively 300 channels and I let the user scroll until next week (data is paginated), which means there's a lot of data. When I scroll until "tomorrow" page, I load more data from my web service, invalidate the layout, reloadData on the collectionView and eventually call `layoutIfNeeded` on my collectionView. Reloading data & `layoutIfNeeded` take up to 10seconds.

After checking the layout code, it seems like disabling the cache in `startDateForIndexPath:` and `endDateForIndexPath:`fixes the issue.

What do you think about it?

**Comment by m1entus** [comment]
Should be fixed, there was some bug with NSMutableIndexPath http://stackoverflow.com/questions/19613927/issues-using-nsindexpath-as-key-in-nsmutabledictionary

**Comment by delannoyk** [comment]
I'll give it a try! Thank you :)
