### ISSUE TITLE
time indicator

### ISSUE THREAD

**Issue by priore** [inspace-io/INSElectronicProgramGuideLayout#7]
Hello, its a great great work!!

The my question; in your example you provided the ISCurrentTimeIndicatorView class, but how to use it?

thanks for your work.

**Comment by m1entus** [comment]
You need to register it as decorator view of kind `INSEPGLayoutElementKindCurrentTimeIndicator`.
`[self.collectionViewEPGLayout registerClass:ISCurrentTimeIndicatorView.class forDecorationViewOfKind: INSEPGLayoutElementKindCurrentTimeIndicator];`

**Comment by priore** [comment]
sorry, but also by adding this line in the example I still do not see it.

**Comment by m1entus** [comment]
*registerNib insted of class and you will see it
