### ISSUE TITLE
CoreData+MagicalRecord.h  file not found

### ISSUE THREAD

**Issue by Changzw** [inspace-io/INSElectronicProgramGuideLayout#9]
I have run the Example target in from INSElectronicProgramGuideLayout.xcworkspace, but can't find CoreData+MagicalRecord.h file

**Comment by m1entus** [comment]
You must install pods

**Comment by Changzw** [comment]
…… I had installed pods。
change  CoreData+MagicalRecord.h  to  MagicalRecord/MagicalRecord.h in prefix.h.

**Comment by m1entus** [comment]
Example can be quite old, will you make PR for this ?
